### ISSUE TITLE
Invite to GemMaintainers

### ISSUE THREAD

**Issue by gemtainers** [gucki/plupload-rails#34]
@gucki I invite to GemMaintainers with this gem.

Becouse of CanCan, StateMachine and others I deside to create OpenSource organization to maintain gems.

People disappear, lose their passion about coding, get new interests, families, children. But if us many we can support gems much longer.

I dont pretend to be an expierenced ruby developer, but I can do administarative work: managing teams, members, approve simple pool-requests: like #33 and #31 

For others who reading this issue:

If you think it good idea and want to support some inactive gems, not life time, maybe just a little - welcome to organization.

I think there is two ways to reanimate gem:

1) Current maintainer can transfer gem

2) If maintainer have no response - we can add to gem prefix 'gt-' and publish it under new name

https://github.com/GemMaintainers

**Comment by gucki** [comment]
Is this project still alive?
