### ISSUE TITLE
Rails 4 asset error

### ISSUE THREAD

**Issue by kyoyk** [gucki/plupload-rails#35]
Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( jquery.plupload.queue/buttons.png )` to `config/initializers/assets.rb` and restart your server

**Comment by create-renegr** [comment]
For reference:
I had to add those ``jquery.plupload.queue/*.png jquery.plupload.queue/*.gif Moxie.swf Moxie.xap``

Rails 4.1

**Comment by gucki** [comment]
Should be fixed when #31 is merged.
